<?php declare(strict_types=1); ?>
<header class="page-header"><div><h1>Mitglieder</h1><p>Stammdaten, Kontakte und Einwilligungen zentral verwalten.</p></div><div class="header-actions"><button class="button button-secondary" type="button" data-coming-soon="true"><svg><use href="#i-upload"/></svg>Importieren</button><button class="button button-primary" type="button" data-dialog-open="member-dialog"><svg><use href="#i-plus"/></svg>Mitglied anlegen</button></div></header>
<div class="members-layout <?= $selected ? 'has-drawer' : '' ?>">
<section class="members-list"><form class="filterbar" method="get" action="/members"><label class="filter-search"><svg><use href="#i-search"/></svg><input type="search" name="search" value="<?= e($search) ?>" placeholder="Mitglieder durchsuchen …"></label><label><span>Status</span><select name="status" data-auto-submit><option value="">Alle</option><option value="active" <?= $status==='active'?'selected':'' ?>>Aktiv</option><option value="paused" <?= $status==='paused'?'selected':'' ?>>Pausiert</option><option value="left" <?= $status==='left'?'selected':'' ?>>Ausgetreten</option></select></label><strong><?= count($members) ?> Mitglieder</strong></form>
<div class="panel table-wrap members-table"><table><thead><tr><th>Name</th><th>Mitgliedsart</th><th>Alter</th><th>Eintritt</th><th>Kontakt</th><th>Einwilligungen</th><th>Status</th><th><span class="sr-only">Aktionen</span></th></tr></thead><tbody>
<?php if ($members === []): ?><tr><td class="empty-cell" colspan="8">Keine Mitglieder für diese Auswahl gefunden.</td></tr><?php endif; ?>
<?php foreach ($members as $member): ?><tr class="<?= (int)($selected['id']??0)===(int)$member['id']?'is-selected':'' ?>" data-row-link="/members?member=<?= (int)$member['id'] ?>"><td><strong><?= e($member['first_name'].' '.$member['last_name']) ?></strong></td><td><?= $member['member_type']==='staff'?'Betreuer/in':'Jugendmitglied' ?></td><td><?= e(age_from_birthdate($member['birth_date'])) ?></td><td><?= e(german_date($member['entry_date'])) ?></td><td><?= e($member['email'] ?: $member['phone'] ?: '–') ?></td><td><span class="consent-count <?= (int)$member['consents_granted'] < (int)$member['consents_total'] ? 'has-open' : '' ?>"><?= (int)$member['consents_granted'] ?> / <?= (int)$member['consents_total'] ?></span></td><td><span class="dot dot-<?= e($member['status_name']) ?>"></span><?= $member['status_name']==='active'?'Aktiv':($member['status_name']==='paused'?'Pausiert':'Ausgetreten') ?></td><td><a class="row-action" href="/members?member=<?= (int)$member['id'] ?>" aria-label="Details öffnen">•••</a></td></tr><?php endforeach; ?>
</tbody></table></div><footer class="list-footer"><span>1–<?= count($members) ?> von <?= count($members) ?> Mitgliedern</span><span>25 Einträge pro Seite</span></footer></section>
<?php if ($selected): ?><aside class="detail-drawer"><header><h2><?= e($selected['first_name'].' '.$selected['last_name']) ?></h2><a class="icon-button" href="/members" aria-label="Schließen"><svg><use href="#i-close"/></svg></a></header><div class="person-summary"><span class="avatar avatar-large"><?= e(initials($selected['first_name'],$selected['last_name'])) ?></span><div><h3><?= e($selected['first_name'].' '.$selected['last_name']) ?></h3><span class="member-active"><i></i>Aktiv</span><p><?= $selected['member_type']==='staff'?'Betreuer/in':'Jugendmitglied' ?> · <?= e(age_from_birthdate($selected['birth_date'])) ?> Jahre<br>Seit <?= e(german_date($selected['entry_date'])) ?></p></div></div>
<section><h3>Kontakt (Erziehungsberechtigte/r)</h3><?php if ($selected['guardian']): ?><p><strong><?= e($selected['guardian']['full_name']) ?></strong><br><?= e($selected['guardian']['phone'] ?: '') ?><br><?= e($selected['guardian']['email'] ?: '') ?></p><?php else: ?><p>Noch kein Kontakt hinterlegt.</p><?php endif; ?></section>
<section><h3>Einwilligungen</h3><?php if ($selected['consents']===[]): ?><p>Noch keine Einwilligungen hinterlegt.</p><?php endif; ?><?php foreach ($selected['consents'] as $consent): ?><div class="drawer-line"><span class="dot dot-<?= $consent['status_name']==='granted'?'active':'paused' ?>"></span><span><strong><?= e($consent['title']) ?></strong><small><?= $consent['status_name']==='granted'?'Erteilt':'Offen' ?></small></span></div><?php endforeach; ?></section>
<footer><button type="button" class="button button-primary button-block" data-dialog-open="member-edit-dialog">Profil bearbeiten</button></footer></aside><?php endif; ?>
</div>
<dialog class="modal" id="member-dialog"><form method="post" action="/members" class="modal-card"><?= csrf_field() ?><header><div><h2>Mitglied anlegen</h2><p>Erfasse zunächst die wichtigsten Stammdaten.</p></div><button type="button" class="icon-button" data-dialog-close aria-label="Schließen"><svg><use href="#i-close"/></svg></button></header>
<?php if ($errors): ?><div class="form-alert">Bitte prüfe die markierten Angaben.</div><?php endif; ?><div class="form-grid"><label>Vorname<input name="first_name" required value="<?= e($_POST['first_name']??'') ?>"></label><label>Nachname<input name="last_name" required value="<?= e($_POST['last_name']??'') ?>"></label><label>Geburtsdatum<input type="date" name="birth_date" value="<?= e($_POST['birth_date']??'') ?>"></label><label>Eintrittsdatum<input type="date" name="entry_date" value="<?= e($_POST['entry_date']??'') ?>"></label><label>Mitgliedsart<select name="member_type"><option value="youth">Jugendmitglied</option><option value="staff">Betreuer/in</option></select></label><label>Telefon<input type="tel" name="phone"></label><label class="span-2">E-Mail-Adresse<input type="email" name="email"></label></div><footer><button type="button" class="button button-secondary" data-dialog-close>Abbrechen</button><button type="submit" class="button button-primary">Mitglied speichern</button></footer></form></dialog>
<?php if ($errors): ?><script>window.addEventListener('DOMContentLoaded',()=>document.getElementById('member-dialog')?.showModal())</script><?php endif; ?>
<?php if ($selected): ?><dialog class="modal" id="member-edit-dialog"><form method="post" action="/members" class="modal-card"><?= csrf_field() ?><input type="hidden" name="member_id" value="<?= (int)$selected['id'] ?>"><header><div><h2>Mitglied bearbeiten</h2><p>Stammdaten, Kontakt und Einwilligung aktualisieren.</p></div><button type="button" class="icon-button" data-dialog-close aria-label="Schließen"><svg><use href="#i-close"/></svg></button></header><div class="form-grid"><label>Vorname<input name="first_name" required value="<?= e($selected['first_name']) ?>"></label><label>Nachname<input name="last_name" required value="<?= e($selected['last_name']) ?>"></label><label>Geburtsdatum<input type="date" name="birth_date" value="<?= e($selected['birth_date']??'') ?>"></label><label>Eintrittsdatum<input type="date" name="entry_date" value="<?= e($selected['entry_date']??'') ?>"></label><label>Mitgliedsart<select name="member_type"><option value="youth" <?= $selected['member_type']==='youth'?'selected':'' ?>>Jugendmitglied</option><option value="staff" <?= $selected['member_type']==='staff'?'selected':'' ?>>Betreuer/in</option></select></label><label>Telefon<input name="phone" value="<?= e($selected['phone']??'') ?>"></label><label class="span-2">E-Mail-Adresse<input type="email" name="email" value="<?= e($selected['email']??'') ?>"></label><label>Erziehungsberechtigte/r<input name="guardian_name" value="<?= e($selected['guardian']['full_name']??'') ?>"></label><label>Beziehung<input name="guardian_relationship" value="<?= e($selected['guardian']['relationship_name']??'') ?>"></label><label>Kontakttelefon<input name="guardian_phone" value="<?= e($selected['guardian']['phone']??'') ?>"></label><label>Kontakt-E-Mail<input type="email" name="guardian_email" value="<?= e($selected['guardian']['email']??'') ?>"></label><label>Einwilligung hinzufügen<input name="consent_title" placeholder="z. B. Foto- und Mediennutzung"></label><label>Status<select name="consent_status"><option value="open">Offen</option><option value="granted">Erteilt</option><option value="declined">Abgelehnt</option></select></label><label class="span-2">Notizen<textarea name="notes_text" rows="3"><?= e($selected['notes_text']??'') ?></textarea></label></div><footer><button type="button" class="button button-secondary" data-dialog-close>Abbrechen</button><button type="submit" class="button button-primary">Änderungen speichern</button></footer></form></dialog><?php endif; ?>
