<?php
declare(strict_types=1);
require dirname(__DIR__, 2) . '/app/bootstrap.php';
Auth::requireLogin();
if (!Auth::isAdmin()) { http_response_code(403); exit('Nur Administratoren dürfen die Mandantenzentrale öffnen.'); }
if (!TenantAccess::tableExists('tenant_roles')) { redirect('../update/'); }

$tenantId=tenant_id(); $user=Auth::user();
$permissions=['manage_records'=>'Fachdaten bearbeiten','manage_members'=>'Mitglieder verwalten','manage_events'=>'Dienste verwalten','manage_attendance'=>'Anwesenheit erfassen','manage_documents'=>'Dokumente verwalten','manage_users'=>'Benutzer verwalten','view_reports'=>'Auswertungen ansehen'];
$modules=['members'=>'Mitglieder','events'=>'Dienste & Übungen','attendance'=>'Anwesenheit','qualifications'=>'Qualifikationen','documents'=>'Dokumente','reports'=>'Auswertungen'];
$widgets=['birthdays'=>'Geburtstage','consents'=>'Einwilligungsfristen','next_event'=>'Nächster Dienst','quick_actions'=>'Schnellzugriff','activity'=>'Letzte Aktivitäten'];

function management_redirect(string $tab): never { header('Location: index.php?tab='.urlencode($tab)); exit; }
function hex_color(string $value, string $fallback): string { return preg_match('/^#[0-9a-f]{6}$/i',$value) ? strtolower($value) : $fallback; }

if (isset($_GET['backup'])) {
    $id=(int)$_GET['backup']; $stmt=db()->prepare("SELECT * FROM saas_backups WHERE id=? AND tenant_id=? AND status_name='completed'"); $stmt->execute([$id,$tenantId]); $backup=$stmt->fetch();
    $file=$backup ? APP_ROOT.'/storage/tenant-backups/'.$tenantId.'/'.basename((string)$backup['file_name']) : '';
    if (!$backup || !is_file($file)) { http_response_code(404); exit('Sicherung nicht gefunden.'); }
    header('Content-Type: application/json'); header('Content-Disposition: attachment; filename="'.basename($file).'"'); header('Content-Length: '.filesize($file)); readfile($file); exit;
}
if (isset($_GET['privacy_export'])) {
    $memberId=(int)$_GET['privacy_export']; $stmt=db()->prepare('SELECT * FROM members WHERE id=? AND tenant_id=?'); $stmt->execute([$memberId,$tenantId]); $member=$stmt->fetch();
    if (!$member) { http_response_code(404); exit('Mitglied nicht gefunden.'); }
    $export=['generated_at'=>date(DATE_ATOM),'member'=>$member];
    foreach (['member_guardians','member_consents','member_documents','member_qualifications','event_responses','attendance'] as $table) { $q=db()->prepare("SELECT * FROM {$table} WHERE tenant_id=? AND member_id=?"); $q->execute([$tenantId,$memberId]); $export[$table]=$q->fetchAll(); }
    audit('privacy_export','members',$memberId,'DSGVO-Datenexport erstellt');
    header('Content-Type: application/json; charset=utf-8'); header('Content-Disposition: attachment; filename="dsgvo-export-'.$memberId.'-'.date('Y-m-d').'.json"'); echo json_encode($export,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES); exit;
}

if ($_SERVER['REQUEST_METHOD']==='POST') {
    require_csrf(); $action=(string)($_POST['action']??'');
    try {
        if (TenantAccess::readOnly() && !in_array($action,['notification_read'],true)) throw new RuntimeException('Der Mandant befindet sich im Lesemodus. Änderungen sind derzeit gesperrt.');
        if ($action==='role_save') {
            $name=trim((string)($_POST['name']??'')); if($name==='') throw new RuntimeException('Bitte einen Rollennamen angeben.');
            db()->beginTransaction(); $stmt=db()->prepare('INSERT INTO tenant_roles (tenant_id,name,description) VALUES (?,?,?)'); $stmt->execute([$tenantId,$name,trim((string)($_POST['description']??''))?:null]); $roleId=(int)db()->lastInsertId();
            $insert=db()->prepare('INSERT INTO tenant_role_permissions (role_id,permission_key) VALUES (?,?)'); foreach((array)($_POST['permissions']??[]) as $permission){ if(isset($permissions[$permission]))$insert->execute([$roleId,$permission]); }
            db()->commit(); audit('create','tenant_roles',$roleId,'Mandantenrolle erstellt: '.$name); flash('success','Rolle wurde angelegt.'); management_redirect('roles');
        }
        if ($action==='role_assign') {
            $uid=(int)$_POST['user_id']; $rid=(int)$_POST['role_id'];
            $check=db()->prepare('SELECT COUNT(*) FROM users u JOIN tenant_roles r ON r.tenant_id=u.tenant_id WHERE u.id=? AND u.tenant_id=? AND r.id=?'); $check->execute([$uid,$tenantId,$rid]); if(!(int)$check->fetchColumn()) throw new RuntimeException('Benutzer oder Rolle ungültig.');
            db()->prepare('INSERT INTO tenant_user_roles (tenant_id,user_id,role_id) VALUES (?,?,?) ON DUPLICATE KEY UPDATE role_id=VALUES(role_id)')->execute([$tenantId,$uid,$rid]); audit('update','users',$uid,'Mandantenrolle zugewiesen'); flash('success','Rolle wurde zugewiesen.'); management_redirect('roles');
        }
        if ($action==='modules_save') {
            $stmt=db()->prepare('INSERT INTO tenant_modules (tenant_id,module_key,is_enabled) VALUES (?,?,?) ON DUPLICATE KEY UPDATE is_enabled=VALUES(is_enabled)'); foreach($modules as $key=>$label)$stmt->execute([$tenantId,$key,isset($_POST['modules'][$key])?1:0]);
            audit('update','tenant_modules',null,'Modulfreigaben aktualisiert'); flash('success','Module wurden gespeichert.'); management_redirect('modules');
        }
        if ($action==='branding_save') {
            $primary=hex_color((string)($_POST['primary_color']??''),'#d71920'); $secondary=hex_color((string)($_POST['secondary_color']??''),'#102b4e');
            db()->prepare('INSERT INTO saas_tenant_settings (tenant_id,display_name,primary_color,secondary_color,dashboard_title) VALUES (?,?,?,?,?) ON DUPLICATE KEY UPDATE display_name=VALUES(display_name),primary_color=VALUES(primary_color),secondary_color=VALUES(secondary_color),dashboard_title=VALUES(dashboard_title)')->execute([$tenantId,trim((string)$_POST['display_name'])?:null,$primary,$secondary,trim((string)$_POST['dashboard_title'])?:null]);
            if(isset($_FILES['logo']) && (int)$_FILES['logo']['error']===UPLOAD_ERR_OK){ if((int)$_FILES['logo']['size']>2*1024*1024)throw new RuntimeException('Das Logo darf maximal 2 MB groß sein.'); $mime=(new finfo(FILEINFO_MIME_TYPE))->file($_FILES['logo']['tmp_name']); $ext=['image/png'=>'png','image/jpeg'=>'jpg','image/svg+xml'=>'svg'][$mime]??null; if(!$ext)throw new RuntimeException('Erlaubt sind PNG, JPG und SVG.'); $dir=APP_ROOT.'/storage/tenant-branding/'.$tenantId; if(!is_dir($dir))mkdir($dir,0750,true); $name='logo.'.$ext; if(!move_uploaded_file($_FILES['logo']['tmp_name'],$dir.'/'.$name))throw new RuntimeException('Logo konnte nicht gespeichert werden.'); db()->prepare('UPDATE saas_tenant_settings SET logo_path=? WHERE tenant_id=?')->execute([$name,$tenantId]); }
            audit('update','saas_tenant_settings',$tenantId,'Mandanten-Branding aktualisiert'); flash('success','Branding wurde gespeichert.'); management_redirect('branding');
        }
        if ($action==='widgets_save') {
            $stmt=db()->prepare('INSERT INTO tenant_dashboard_widgets (tenant_id,widget_key,is_visible,sort_order) VALUES (?,?,?,?) ON DUPLICATE KEY UPDATE is_visible=VALUES(is_visible),sort_order=VALUES(sort_order)'); $order=10; foreach($widgets as $key=>$label){$stmt->execute([$tenantId,$key,isset($_POST['widgets'][$key])?1:0,$order]);$order+=10;}
            audit('update','tenant_dashboard_widgets',null,'Dashboard-Konfiguration gespeichert'); flash('success','Dashboard wurde konfiguriert.'); management_redirect('dashboard');
        }
        if ($action==='privacy_create') {
            $mid=(int)$_POST['member_id']; $type=in_array($_POST['request_type']??'', ['export','anonymize','delete'],true)?$_POST['request_type']:'export'; $check=db()->prepare('SELECT COUNT(*) FROM members WHERE id=? AND tenant_id=?');$check->execute([$mid,$tenantId]);if(!(int)$check->fetchColumn())throw new RuntimeException('Mitglied nicht gefunden.');
            $stmt=db()->prepare('INSERT INTO tenant_privacy_requests (tenant_id,member_id,request_type,requested_by,due_at,notes_text) VALUES (?,?,?,?,DATE_ADD(CURDATE(),INTERVAL 30 DAY),?)');$stmt->execute([$tenantId,$mid,$type,(int)$user['id'],trim((string)($_POST['notes_text']??''))?:null]);audit('create','tenant_privacy_requests',(int)db()->lastInsertId(),'DSGVO-Vorgang angelegt');flash('success','DSGVO-Vorgang wurde angelegt.');management_redirect('privacy');
        }
        if ($action==='backup_create') {
            $tables=['organizations','users','members','events','attendance','member_guardians','member_consents','event_responses','member_documents','event_templates','qualifications','member_qualifications']; $data=['version'=>1,'tenant_id'=>$tenantId,'created_at'=>date(DATE_ATOM),'tables'=>[]];
            foreach($tables as $table){$q=$table==='organizations'?db()->prepare('SELECT * FROM organizations WHERE id=?'):db()->prepare("SELECT * FROM {$table} WHERE tenant_id=?");$q->execute([$tenantId]);$data['tables'][$table]=$q->fetchAll();}
            $dir=APP_ROOT.'/storage/tenant-backups/'.$tenantId;if(!is_dir($dir)&&!mkdir($dir,0750,true)&&!is_dir($dir))throw new RuntimeException('Sicherungsverzeichnis konnte nicht erstellt werden.');$file='tenant-'.$tenantId.'-'.date('Ymd-His').'-'.bin2hex(random_bytes(3)).'.json';$json=json_encode($data,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);if(file_put_contents($dir.'/'.$file,$json,LOCK_EX)===false)throw new RuntimeException('Sicherung konnte nicht geschrieben werden.');
            db()->prepare("INSERT INTO saas_backups (tenant_id,created_by,file_name,file_size,backup_type,status_name,completed_at) VALUES (?,?,?,?,?,'completed',NOW())")->execute([$tenantId,(int)$user['id'],$file,strlen($json),'manual']);audit('create','saas_backups',(int)db()->lastInsertId(),'Mandantensicherung erstellt');flash('success','Sicherung wurde erstellt.');management_redirect('backup');
        }
        if ($action==='restore_request') { $id=(int)$_POST['backup_id'];db()->prepare("UPDATE saas_backups SET restore_requested_at=NOW() WHERE id=? AND tenant_id=? AND status_name='completed'")->execute([$id,$tenantId]);audit('restore_request','saas_backups',$id,'Wiederherstellung zur Betreiberprüfung angefordert');flash('success','Wiederherstellung wurde sicher zur Betreiberprüfung angefordert.');management_redirect('backup'); }
        if ($action==='notification_read') { db()->prepare('UPDATE saas_notifications SET read_at=NOW() WHERE id=? AND tenant_id=? AND (user_id IS NULL OR user_id=?)')->execute([(int)$_POST['id'],$tenantId,(int)$user['id']]); management_redirect('notifications'); }
    } catch(Throwable $e){ if(db()->inTransaction())db()->rollBack(); flash('error',$e->getMessage()); management_redirect((string)($_GET['tab']??'overview')); }
}

$tab=in_array($_GET['tab']??'overview',['overview','roles','modules','branding','dashboard','privacy','backup','notifications'],true)?(string)$_GET['tab']:'overview';$flash=pull_flash();$settings=TenantAccess::settings();$subscription=TenantAccess::subscription();
$roleRows=db()->prepare('SELECT r.*,GROUP_CONCAT(rp.permission_key) permissions FROM tenant_roles r LEFT JOIN tenant_role_permissions rp ON rp.role_id=r.id WHERE r.tenant_id=? GROUP BY r.id ORDER BY r.name');$roleRows->execute([$tenantId]);$roles=$roleRows->fetchAll();
$usersStmt=db()->prepare('SELECT u.id,u.first_name,u.last_name,u.role,ur.role_id,r.name custom_role FROM users u LEFT JOIN tenant_user_roles ur ON ur.user_id=u.id AND ur.tenant_id=u.tenant_id LEFT JOIN tenant_roles r ON r.id=ur.role_id WHERE u.tenant_id=? ORDER BY u.last_name');$usersStmt->execute([$tenantId]);$users=$usersStmt->fetchAll();
$moduleStmt=db()->prepare('SELECT module_key,is_enabled FROM tenant_modules WHERE tenant_id=?');$moduleStmt->execute([$tenantId]);$moduleState=array_column($moduleStmt->fetchAll(),'is_enabled','module_key');
$widgetStmt=db()->prepare('SELECT widget_key,is_visible FROM tenant_dashboard_widgets WHERE tenant_id=?');$widgetStmt->execute([$tenantId]);$widgetState=array_column($widgetStmt->fetchAll(),'is_visible','widget_key');
$membersStmt=db()->prepare('SELECT id,first_name,last_name FROM members WHERE tenant_id=? ORDER BY last_name,first_name');$membersStmt->execute([$tenantId]);$members=$membersStmt->fetchAll();
$privacyStmt=db()->prepare('SELECT p.*,CONCAT(m.first_name," ",m.last_name) member_name FROM tenant_privacy_requests p LEFT JOIN members m ON m.id=p.member_id WHERE p.tenant_id=? ORDER BY p.created_at DESC');$privacyStmt->execute([$tenantId]);$privacy=$privacyStmt->fetchAll();
$backupStmt=db()->prepare('SELECT * FROM saas_backups WHERE tenant_id=? ORDER BY created_at DESC LIMIT 30');$backupStmt->execute([$tenantId]);$backups=$backupStmt->fetchAll();
$notificationStmt=db()->prepare('SELECT * FROM saas_notifications WHERE tenant_id=? AND (user_id IS NULL OR user_id=?) ORDER BY created_at DESC LIMIT 50');$notificationStmt->execute([$tenantId,(int)$user['id']]);$notifications=$notificationStmt->fetchAll();
$used=['members'=>TenantAccess::usage('members'),'users'=>TenantAccess::usage('users'),'storage'=>TenantAccess::usage('storage_mb')];
?><!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Mandantenzentrale · JF-SYSTEM.de</title><link rel="stylesheet" href="<?=e(asset_url('app.css'))?>"><style>.manage-tabs{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:22px}.manage-tabs a{padding:9px 12px;border-radius:9px;background:#fff;border:1px solid var(--line);text-decoration:none;color:var(--navy-900);font-weight:700}.manage-tabs a.active{background:var(--navy-900);color:#fff}.manage-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.manage-card{background:#fff;border:1px solid var(--line);border-radius:14px;padding:20px}.manage-card h3{margin:0 0 8px}.manage-card strong{font-size:25px}.check-list{display:grid;gap:10px}.check-list label{display:flex;gap:9px;align-items:center}.inline-form{display:flex;gap:10px;align-items:end;flex-wrap:wrap}.inline-form .field{min-width:180px;flex:1}.muted{color:var(--muted)}@media(max-width:850px){.manage-grid{grid-template-columns:1fr}}</style></head><body><main class="content" style="max-width:1250px;margin:auto"><div class="page-head"><div><h1>Mandantenzentrale</h1><p><?=e($user['organization_name'])?> · <?=e($subscription['plan_name']??'ohne Tarif')?></p></div><a class="btn btn-secondary" href="../?page=settings">Zur Anwendung</a></div><?php if($flash):?><div class="flash <?=$flash['type']==='error'?'flash-error':''?>"><?=e($flash['message'])?></div><?php endif;?><nav class="manage-tabs"><?php foreach(['overview'=>'Übersicht','roles'=>'Rollen','modules'=>'Module','branding'=>'Branding','dashboard'=>'Dashboard','privacy'=>'DSGVO','backup'=>'Backups','notifications'=>'Meldungen'] as $key=>$label):?><a class="<?=$tab===$key?'active':''?>" href="?tab=<?=$key?>"><?=e($label)?></a><?php endforeach;?></nav>
<?php if($tab==='overview'):?><div class="manage-grid"><div class="manage-card"><h3>Mitglieder</h3><strong><?=$used['members']?> / <?=isset($subscription['member_limit'])&&$subscription['member_limit']!==null?(int)$subscription['member_limit']:'∞'?></strong></div><div class="manage-card"><h3>Benutzer</h3><strong><?=$used['users']?> / <?=isset($subscription['user_limit'])&&$subscription['user_limit']!==null?(int)$subscription['user_limit']:'∞'?></strong></div><div class="manage-card"><h3>Speicher</h3><strong><?=$used['storage']?> / <?=isset($subscription['storage_limit_mb'])&&$subscription['storage_limit_mb']!==null?(int)$subscription['storage_limit_mb']:'∞'?> MB</strong></div></div><section class="panel" style="margin-top:20px"><div class="panel-body"><h2>Status: <?=TenantAccess::readOnly()?'Lesemodus':'Aktiv'?></h2><p class="muted">Tarif: <?=e($subscription['plan_name']??'Nicht zugeordnet')?> · Abo-Status: <?=e($subscription['status_name']??'unbekannt')?></p></div></section>
<?php elseif($tab==='roles'):?><section class="panel"><div class="panel-head"><h2>Neue Rolle</h2></div><div class="panel-body"><form method="post" class="form-grid"><?=csrf_field()?><input type="hidden" name="action" value="role_save"><div class="field"><label>Name</label><input name="name" required></div><div class="field"><label>Beschreibung</label><input name="description"></div><div class="field field-full check-list"><?php foreach($permissions as $key=>$label):?><label><input type="checkbox" name="permissions[]" value="<?=e($key)?>"> <?=e($label)?></label><?php endforeach;?></div><button class="btn btn-primary">Rolle anlegen</button></form></div></section><section class="panel"><div class="panel-head"><h2>Zuweisungen</h2></div><div class="panel-body"><?php foreach($users as $u):?><form method="post" class="inline-form" style="margin-bottom:12px"><?=csrf_field()?><input type="hidden" name="action" value="role_assign"><input type="hidden" name="user_id" value="<?=(int)$u['id']?>"><strong><?=e($u['last_name'].', '.$u['first_name'])?></strong><select name="role_id" required><option value="">Rolle wählen</option><?php foreach($roles as $r):?><option value="<?=(int)$r['id']?>" <?=(int)$u['role_id']===(int)$r['id']?'selected':''?>><?=e($r['name'])?></option><?php endforeach;?></select><button class="btn btn-secondary">Zuweisen</button></form><?php endforeach;?></div></section>
<?php elseif($tab==='modules'):?><section class="panel"><div class="panel-head"><h2>Module freigeben</h2></div><div class="panel-body"><form method="post" class="check-list"><?=csrf_field()?><input type="hidden" name="action" value="modules_save"><?php foreach($modules as $key=>$label):?><label><input type="checkbox" name="modules[<?=$key?>]" value="1" <?=!isset($moduleState[$key])||(int)$moduleState[$key]===1?'checked':''?>> <?=e($label)?></label><?php endforeach;?><button class="btn btn-primary">Module speichern</button></form></div></section>
<?php elseif($tab==='branding'):?><section class="panel"><div class="panel-head"><h2>Erscheinungsbild</h2></div><div class="panel-body"><form method="post" enctype="multipart/form-data" class="form-grid"><?=csrf_field()?><input type="hidden" name="action" value="branding_save"><div class="field"><label>Anzeigename</label><input name="display_name" value="<?=e($settings['display_name'])?>"></div><div class="field"><label>Dashboard-Titel</label><input name="dashboard_title" value="<?=e($settings['dashboard_title'])?>"></div><div class="field"><label>Primärfarbe</label><input type="color" name="primary_color" value="<?=e($settings['primary_color'])?>"></div><div class="field"><label>Navigationsfarbe</label><input type="color" name="secondary_color" value="<?=e($settings['secondary_color'])?>"></div><div class="field field-full"><label>Logo (PNG, JPG oder SVG, max. 2 MB)</label><input type="file" name="logo" accept=".png,.jpg,.jpeg,.svg"></div><button class="btn btn-primary">Branding speichern</button></form></div></section>
<?php elseif($tab==='dashboard'):?><section class="panel"><div class="panel-head"><h2>Dashboard-Bausteine</h2></div><div class="panel-body"><form method="post" class="check-list"><?=csrf_field()?><input type="hidden" name="action" value="widgets_save"><?php foreach($widgets as $key=>$label):?><label><input type="checkbox" name="widgets[<?=$key?>]" value="1" <?=!isset($widgetState[$key])||(int)$widgetState[$key]===1?'checked':''?>> <?=e($label)?></label><?php endforeach;?><button class="btn btn-primary">Dashboard speichern</button></form></div></section>
<?php elseif($tab==='privacy'):?><section class="panel"><div class="panel-head"><h2>DSGVO-Vorgang anlegen</h2></div><div class="panel-body"><form method="post" class="form-grid"><?=csrf_field()?><input type="hidden" name="action" value="privacy_create"><div class="field"><label>Mitglied</label><select name="member_id" required><?php foreach($members as $m):?><option value="<?=(int)$m['id']?>"><?=e($m['last_name'].', '.$m['first_name'])?></option><?php endforeach;?></select></div><div class="field"><label>Vorgang</label><select name="request_type"><option value="export">Datenexport</option><option value="anonymize">Anonymisierung prüfen</option><option value="delete">Löschung prüfen</option></select></div><div class="field field-full"><label>Notiz</label><input name="notes_text"></div><button class="btn btn-primary">Vorgang anlegen</button></form></div></section><section class="panel"><div class="table-wrap"><table class="data-table"><tr><th>Mitglied</th><th>Art</th><th>Status</th><th>Frist</th><th></th></tr><?php foreach($privacy as $p):?><tr><td><?=e($p['member_name']??'–')?></td><td><?=e($p['request_type'])?></td><td><?=e($p['status_name'])?></td><td><?=e(format_date($p['due_at']))?></td><td><?php if($p['member_id']):?><a class="btn btn-secondary btn-small" href="?privacy_export=<?=(int)$p['member_id']?>">Export laden</a><?php endif;?></td></tr><?php endforeach;?></table></div></section>
<?php elseif($tab==='backup'):?><section class="panel"><div class="panel-head"><h2>Mandantensicherungen</h2><form method="post"><?=csrf_field()?><input type="hidden" name="action" value="backup_create"><button class="btn btn-primary">Neue Sicherung</button></form></div><div class="table-wrap"><table class="data-table"><tr><th>Datei</th><th>Erstellt</th><th>Status</th><th>Wiederherstellung</th><th></th></tr><?php foreach($backups as $b):?><tr><td><?=e($b['file_name'])?></td><td><?=e(format_date($b['created_at'],true))?></td><td><?=e($b['status_name'])?></td><td><?=!empty($b['restore_requested_at'])?'angefordert':'–'?></td><td><div class="row-actions"><a class="btn btn-secondary btn-small" href="?backup=<?=(int)$b['id']?>">Download</a><form method="post" data-confirm="Wiederherstellung zur Betreiberprüfung anfordern?"><?=csrf_field()?><input type="hidden" name="action" value="restore_request"><input type="hidden" name="backup_id" value="<?=(int)$b['id']?>"><button class="btn btn-secondary btn-small">Wiederherstellen</button></form></div></td></tr><?php endforeach;?></table></div></section>
<?php else:?><section class="panel"><div class="table-wrap"><table class="data-table"><tr><th>Meldung</th><th>Zeit</th><th></th></tr><?php foreach($notifications as $n):?><tr><td><strong><?=e($n['title'])?></strong><small><?=e($n['message_text'])?></small></td><td><?=e(format_date($n['created_at'],true))?></td><td><?php if(!$n['read_at']):?><form method="post"><?=csrf_field()?><input type="hidden" name="action" value="notification_read"><input type="hidden" name="id" value="<?=(int)$n['id']?>"><button class="btn btn-secondary btn-small">Gelesen</button></form><?php else:?>gelesen<?php endif;?></td></tr><?php endforeach;?></table><?php if(!$notifications):?><div class="empty">Keine Meldungen vorhanden.</div><?php endif;?></div></section><?php endif;?></main><script src="<?=e(asset_url('app.js'))?>" defer></script></body></html>
